import React from 'react';
import { Table } from 'react-bootstrap';
import update from 'immutability-helper';
import { ApiKey } from '@innexgo/frontend-auth-api';
import { Link, AddButton, DisplayModal } from '@innexgo/common-react-components';
import { TournamentSubmission, TournamentYear, TournamentYearDemand } from '../utils/api';
import { ViewUser } from './ViewData';

import { Eye as ViewIcon } from 'react-bootstrap-icons';

type ManageTournamentSubmissionsTournamentProps = {
  tournamentSubmissions: TournamentSubmission[],
  tournamentYears: TournamentYear[],
  tournamentYearDemands: TournamentYearDemand[],
  apiKey: ApiKey,
}

function ManageTournamentSubmissionsTournament(props: ManageTournamentSubmissionsTournamentProps) {
  const submissions = props.tournamentSubmissions.map(x => x);
  const years = props.tournamentYears.map(x => x);
  const demands = props.tournamentYearDemands.map(x => x);

  // sort by year ascending
  years.sort((a, b) => a.currentYear - b.currentYear);


  const data = years.map(y => {
    const subs = submissions.filter(s => s.year === y.currentYear);
    // sort by amount descending
    subs.sort((a, b) => b.amount - a.amount);

    return { y, subs }
  });


  return <Table hover bordered>
    <thead>
      <tr>
        <th>Year</th>
        <th>Total Demand</th>
        <th>Profit per Megabarrel</th>
        <th>Production</th>
      </tr>
    </thead>
    <tbody>
      {data.length === 0
        ? <tr><td className="text-center" colSpan={4}>No Years</td></tr>
        : <> </>
      }
      {data.map(d =>
        <tr key={d.y.currentYear}>
          <td>Year {d.y.currentYear + 1}</td>
          <td>2200</td>
          <td>2200</td>
          <td>
            <Table hover bordered>
              <thead>
                <tr>
                  <th>Rank</th>
                  <th>Player</th>
                  <th>Amount</th>
                  <th>Autogenerated?</th>
                </tr>
              </thead>
              <tbody>
                {d.subs.length === 0
                  ? <tr><td className="text-center" colSpan={4}>No Submissions</td></tr>
                  : <> </>
                }
                {d.subs.map((s, i) =>
                  <tr>
                    <td>{i + 1}</td>
                    <td><ViewUser userId={s.creatorUserId} apiKey={props.apiKey} expanded={false} /></td>
                    <td>{s.amount}</td>
                    <td>{s.autogenerated}</td>
                  </tr>
                )}
              </tbody>
            </Table>
          </td>
        </tr>
      )}
    </tbody>
  </Table>
}

export default ManageTournamentSubmissionsTournament;
