use super::db_types::*;
use std::convert::From;
use tokio_postgres::GenericClient;

impl From<tokio_postgres::row::Row> for TournamentSubmission {
    // select * from tournament_submission order only, otherwise it will fail
    fn from(row: tokio_postgres::Row) -> TournamentSubmission {
        TournamentSubmission {
            tournament_submission_id: row.get("tournament_submission_id"),
            creation_time: row.get("creation_time"),
            creator_user_id: row.get("creator_user_id"),
            tournament_id: row.get("tournament_id"),
            amount: row.get("amount"),
            year: row.get("year"),
            autogenerated: row.get("autogenerated"),
        }
    }
}

// TODO we need to figure out a way to make scheduled and unscheduled articles work better
pub async fn add(
    con: &mut impl GenericClient,
    creator_user_id: i64,
    tournament_id: i64,
    year: i64,
    amount: i64,
    autogenerated: bool,
) -> Result<TournamentSubmission, tokio_postgres::Error> {
    let row = con
        .query_one(
            "INSERT INTO
             tournament_submission(
                 creator_user_id,
                 tournament_id,
                 year,
                 amount,
                 autogenerated
             )
             VALUES ($1, $2, $3, $4, $5)
             RETURNING tournament_submission_id, creation_time
            ",
            &[
                &creator_user_id,
                &tournament_id,
                &year,
                &amount,
                &autogenerated,
            ],
        )
        .await?;

    Ok(TournamentSubmission {
        tournament_submission_id: row.get(0),
        creation_time: row.get(1),
        creator_user_id,
        tournament_id,
        year,
        amount,
        autogenerated,
    })
}

pub async fn get_recent_by_tournament(
    con: &mut impl GenericClient,
    tournament_id: i64,
) -> Result<Vec<TournamentSubmission>, tokio_postgres::Error> {
    let sql = [
        "SELECT ts.* FROM recent_tournament_submission ts",
        " WHERE 1 = 1",
        " AND ts.tournament_id = $1",
        " ORDER BY ts.tournament_submission_id",
    ]
    .join("\n");

    let stmnt = con.prepare(&sql).await?;

    let results = con
        .query(&stmnt, &[&tournament_id])
        .await?
        .into_iter()
        .map(|row| row.into())
        .collect();

    Ok(results)
}

pub async fn query(
    con: &mut impl GenericClient,
    props: super::request::TournamentSubmissionViewProps,
) -> Result<Vec<TournamentSubmission>, tokio_postgres::Error> {
    let sql = [
        "SELECT ts.* FROM tournament_submission ts",
        " WHERE 1 = 1",
        " AND ($1::bigint[] IS NULL OR ts.tournament_submission_id = ANY($1))",
        " AND ($2::bigint   IS NULL OR ts.creation_time >= $2)",
        " AND ($3::bigint   IS NULL OR ts.creation_time <= $3)",
        " AND ($4::bigint[] IS NULL OR ts.creator_user_id = ANY($4))",
        " AND ($5::bigint[] IS NULL OR ts.tournament_id = ANY($5))",
        " ORDER BY ts.tournament_submission_id",
    ]
    .join("\n");

    let stmnt = con.prepare(&sql).await?;

    let results = con
        .query(
            &stmnt,
            &[
                &props.tournament_submission_id,
                &props.min_creation_time,
                &props.max_creation_time,
                &props.creator_user_id,
                &props.tournament_id,
            ],
        )
        .await?
        .into_iter()
        .map(|row| row.into())
        .collect();

    Ok(results)
}
